CompileFlags:
  Add:
    - -std=c++23
    - -stdlib=libc++             # Use Appleâ€™s C++ standard library
    - -Wall
    - -Wextra
    - -Wpedantic
    - -Wshadow
    - -Wconversion
    - -fsanitize=address,undefined
    - [-isystem, "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/v1"]
    - [-isystem, "/opt/homebrew/include"]

